# Generated by Django 2.0.5 on 2019-02-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedmaa', '0002_auto_20190212_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(),
        ),
    ]
