# Generated by Django 2.0.5 on 2019-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedmaa', '0004_auto_20190212_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount_spent',
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_proof',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
