# Generated by Django 2.0.5 on 2019-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tedmaa', '0005_auto_20190212_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='upload',
        ),
    ]
