# Generated by Django 2.0.5 on 2019-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedmaa', '0006_remove_event_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateField(),
        ),
    ]
